### PR TITLE
Fixed #736 and #737

### LINKED ISSUE #736: Following Location only for 201, 202 and 3xx status codes
Some domains are sending the Location header even for e.g. 200 status codes. For example the domain minutouno.com or mlssoccer.com

I think that jsoup should follow the Location header only on 201, 202 and 3xx status codes.

### PR DESCRIPTION
**Pull request by Ph3n1x**
#736: Fixed by verifying that the status code is 201, 202 or 3xx.
#737: Fixed by checking that if the response contains no cookies and a location header which points to the same URL as the current request, then stop redirecting.

### CODE REVIEW

**Comment by Ph3n1x** [comment]
Is there any reason not to merge my pull request?

**Comment by Ph3n1x** [comment]
Any reasons why this PR has not been merged yet?

**Comment by cketti** [comment]
I'm not speaking for the maintainer. But I prefer one fix per pull request. Ideally the fix is accompanied by tests. 
Also, try to avoid creating a pull request from your `master` branch. That almost always leads to it including useless merge commits as you keep pulling changes from upstream.

**Comment by jhy** [comment]
Thanks -- too much stuff in here to merge, but have implemented similar redirect fixes, and cookie update in #1476

**Pull request closed without merging**
