### PR TITLE
Find reason of null

### LINKED ISSUE #1756: the addition imprrove for the selectXpath function
in the closed issues "Question about using document.selectXpath() in xhtml #1746" Once XML with namespace is encountered, the corresponding XPath query will have no results. That is not a good thing for packet because it is not a easy thing to know is there XML with namespace in the http file. so my term and I plan to add a judge in it to throw a warning when the this case happen. I think this is important because no one want to get a null without the error message.

### PR DESCRIPTION
**Pull request by QAQGaeBolg**
fix #1756

### CODE REVIEW

**Comment by jhy** [comment]
Thanks, but I don't see this as production ready. I don't know that it's a feature we need, and in this state with printlines it's not a meaningful API. Not inclined to merge.

**Comment by jhy** [comment]
Thanks, but I don't see this as production ready. I don't know that it's a feature we need, and in this state with printlines it's not a meaningful API. Not inclined to merge.

**Comment by susJohnny** [comment]
Sorry to bother you, but this is part of our course project. We don't mean to make any change to the code, just to leave the record and get scores. Could you please keep the commit and pull request record?

**Comment by jhy** [comment]
Thanks for wasting our time on your point scoring, really appreciate it.

**Comment by sol1775** [comment]
No me deja entrar

**Pull request closed without merging**
