### PR TITLE
Added raw data to POST request

### PR DESCRIPTION
**Pull request by purblind**
Jsoup.connect(url).rawData("myRawData").header("Content-Type", "application/json").post();
tests included

### CODE REVIEW

**Comment by alaif** [comment]
Is anyone taking care of this pull request be reviewed/merged or it's kind of abandoned...?

**Comment by purblind** [comment]
I don't think so ;(

**Comment by SubiRUN** [comment]
There are lots of pull requests like this. How about starting a new branch of jsoup that focus more on sending HTTP requests?

**Comment by alaif** [comment]
@SubiRUN Interesting idea. Myself, I am not sure about that. Given such a thing means a lot of work and implies maintenance for someone always.. I moved to httpclient library from Apache where I can perform all kind of standard HTTP requests incl. PUT, DELETE (if I will ever need on that particular project I am working on).

**Comment by songofhawk** [comment]
I thinks this is a useful feature , because it can avoid import another library, such as HttpClient and use different APIs

**Comment by dknebula** [comment]
@jhy  @purblind, can you help to add this codes to the main branch, it's really useful to post raw data..

**Comment by purblind** [comment]
@dknebula I create new pull request #657

**Pull request closed without merging**
