### PR TITLE
Corrected uses of Whitelist to Safelist

### PR DESCRIPTION
**Pull request by jhy**
And introduced a (deprecated) compatibility shim.

Tested with japicmp binary and source compatibility report, and checked binary compat with some test utilities (local testing).

Many thanks to @drei01 (#1408), @nkiesel (#1423) and others for highlighting the issue and for PRs which this commit refines.

### CODE REVIEW

**Comment by jhy** [comment]
(It's annoying that git is losing the rename of Whitelist -> Safelist and so losing the history. Showed as a rename and re-add prior to commit, but not in history. Wonder if separate commits between the rename and the add would have kept clean.)

**Comment by jhy** [comment]
I'm merging now, but would of course love for reviews and to hear any comments from everyone.

**Comment by markaalvaro** [comment]
Do you have any idea when this will be released? I see I can get it in the snapshot, but was wondering if there'd be a stable release anytime soon that includes this change.

**Comment by jhy** [comment]
> Do you have any idea when this will be released?

**Pull request merged**
