### PR TITLE
Refactor into Multimodule and Add jsoup-hamcrest

### PR DESCRIPTION
**Pull request by leonard84**
Refactor Jsoup into a multi module project as a first step for adding `jsoup-hamcrest`

- Update Plugins
- Fix Formatting in poms
- Add Editorconfig
- Fix Javadoc issue in StringUtil.java

Add `jsoup-hamcrest` module (#1053)

Disable Java 7 Build as jsoup-hamcrest needs Java 8. Animal Sniffer
ensures that jsoup stays Java 7 compatible.

### CODE REVIEW

**Comment by leonard84** [comment]
@jhy was on holiday myself, but wanted to check in and see if there is anything you want changed for the PR?

**Comment by leonard84** [comment]
@jhy since you are back, could you take a look at this.

**Comment by leonard84** [comment]
@jhy any chance this might get merged, then I would fix it, otherwise I'd release it as a standalone variant? I would strongly prefer this to be part of jsoup itself.

**Comment by leonard84** [comment]
For those that are interested, here is a standalone release https://github.com/1and1/jsoup-hamcrest 
However, I'd still like to merge it so it can be part of the official jsoup.

**Comment by jhy** [comment]
Hey @leonard84, sorry for the lack of correspondence. I need to take another look at this. Mostly from both not having used multimodule projects, or hamcrest.

**Comment by leonard84** [comment]
@jhy sure, just tell me when you've taken a more in-depth look and would like to merge it, then I can see about updating the pr.

**Comment by leonard84** [comment]
@jhy any chance to take a look yet?

**Comment by jhy** [comment]
(Closing old PRs; thanks for your interest and apologies for the late review. I don't plan to merge this, as I believe Hamcrest is less relevant now, and there is a lot of project complexity coming from the test syntax sugar; but if you believe there is still a value in it or similar, please leave a comment.)

**Comment by leonard84** [comment]
> believe Hamcrest is less relevant now

As opposed to what? It is still the library for assertions with Spring's MockMVC ([1](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/web/servlet/result/ContentResultMatchers.html)), which was the reason I initially created these matchers.

**Pull request closed without merging**
