### PR TITLE
Use Java 8's Consumer interface.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
* Use the `Consumer` interface introduced in Java 8, as it can be backported for older versions of Android via [core library desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring).

### CODE REVIEW

**Comment by jhy** [comment]
Thanks, but can't merge with the build failures. Is there an update mojo sniffer?

And would need to make sure the API change is backwards compatible too.

**Comment by Isira-Seneviratne** [comment]
> Thanks, but can't merge with the build failures. Is there an update mojo sniffer?

I didn't change anything else, so I'm not sure why the build is failing.

> And would need to make sure the API change is backwards compatible too.

With existing calls to `forEach`?

**Comment by jhy** [comment]
The build fails because we use the Mojo Animal Sniffer plugin to verify that all APIs used are in the appropriate Java and Android language levels. It doesn't believe that the Consumer interface is available on Android -- which is why I added that internal workaround.

The error in the build is:

```
Error:  /home/runner/work/jsoup/jsoup/src/main/java/org/jsoup/nodes/Node.java:665: Undefined reference: void java.util.function.Consumer.accept(Object)
Error:  /home/runner/work/jsoup/jsoup/src/main/java/org/jsoup/nodes/Element.java:1825: Undefined reference: void java.util.function.Consumer.accept(Object)
Error:  Failed to execute goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.22:check (animal-sniffer) on project jsoup: Signature errors found. Verify them and ignore them with the proper annotation if needed. -> [Help 1]
```

The check is defined in the POM: https://github.com/jhy/jsoup/blob/29be991198d3b518d64ee36176ae415688468f61/pom.xml#L74-L78

I don't see an [update](https://mvnrepository.com/artifact/net.sf.androidscents.signature/android-api-level-10) to that signature definition that supports the APIs brought in by new desugaring implementation. So we would need to find a different way to do those tests. Or allow-list the API explicitly, or something.

**Comment by Isira-Seneviratne** [comment]
I added an ignore rule for the Mojo Animal Sniffer plugin.

**Comment by jhy** [comment]
Cool - the next issue to resolve is the API backwards compat issue - the interface has changed:

```
Error:  Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.17.1:cmp (default) on project jsoup: There is at least one incompatibility: org.jsoup.helper.Consumer.accept(java.lang.Object):METHOD_REMOVED,org.jsoup.helper.Consumer:SUPERCLASS_REMOVED,org.jsoup.helper.Consumer:CLASS_REMOVED,org.jsoup.helper.Consumer:CLASS_GENERIC_TEMPLATE_CHANGED,org.jsoup.nodes.CDataNode:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.Comment:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.DataNode:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.Document:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.DocumentType:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.Element.forEach(org.jsoup.helper.Consumer):METHOD_REMOVED,org.jsoup.nodes.Element.forEachNode(org.jsoup.helper.Consumer):METHOD_REMOVED,org.jsoup.nodes.Element:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.FormElement:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.Node.forEachNode(org.jsoup.helper.Consumer):METHOD_REMOVED,org.jsoup.nodes.PseudoTextElement:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.TextNode:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.XmlDeclaration:METHOD_REMOVED_IN_SUPERCLASS -> [Help 1]
```

I think we can deal with that by making the jsoup Consumer extend from the Java Consumer, and mark it deprecated for removal in the next release.

**Comment by Isira-Seneviratne** [comment]
> Cool - the next issue to resolve is the API backwards compat issue - the interface has changed:
> 
> ```
> Error:  Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.17.1:cmp (default) on project jsoup: There is at least one incompatibility: org.jsoup.helper.Consumer.accept(java.lang.Object):METHOD_REMOVED,org.jsoup.helper.Consumer:SUPERCLASS_REMOVED,org.jsoup.helper.Consumer:CLASS_REMOVED,org.jsoup.helper.Consumer:CLASS_GENERIC_TEMPLATE_CHANGED,org.jsoup.nodes.CDataNode:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.Comment:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.DataNode:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.Document:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.DocumentType:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.Element.forEach(org.jsoup.helper.Consumer):METHOD_REMOVED,org.jsoup.nodes.Element.forEachNode(org.jsoup.helper.Consumer):METHOD_REMOVED,org.jsoup.nodes.Element:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.FormElement:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.Node.forEachNode(org.jsoup.helper.Consumer):METHOD_REMOVED,org.jsoup.nodes.PseudoTextElement:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.TextNode:METHOD_REMOVED_IN_SUPERCLASS,org.jsoup.nodes.XmlDeclaration:METHOD_REMOVED_IN_SUPERCLASS -> [Help 1]
> ```
> 
> I think we can deal with that by making the jsoup Consumer extend from the Java Consumer, and mark it deprecated for removal in the next release.
> 

Yeah, I was thinking of adding overloaded methods for the separate consumer types, but your solution is much better.

**Comment by Isira-Seneviratne** [comment]
I tried removing the `accept` method in the Jsoup `Consumer`, but Mojo gave an error saying the method had been removed, even though it's there in the parent interface.

**Comment by jhy** [comment]
OK, my commit has deprecated the old methods, and added a temporary deprecated overload for the old version. This ensures both source and binary compatibility in this version.  The next version can remove these methods.

**Comment by jhy** [comment]
Thanks again! Have merged.

**Pull request merged**
