### PR TITLE
fixed issue #916

### PR DESCRIPTION
**Pull request by mccxj**
fixed issue #916 InputStream not closed in class org.jsoup.nodes.Entities.
use jdk7 try-with-resources to close "BufferReader input".

### CODE REVIEW

**Comment by cketti** [comment]
Note: try-with-resources is not supported on Android versions prior to 4.4 (API 19).

**Comment by mccxj** [comment]
@cketti 
try-with-resources is just syntactic sugar, compiled class is also support on Android older version.

**Comment by cketti** [comment]
try-with-resources makes use of [Throwable.addSuppressed(Throwable)](https://developer.android.com/reference/java/lang/Throwable.html#addSuppressed(java.lang.Throwable)) which was officially added with API 19. The method was available on earlier Android versions, but marked as hidden and not part of the official API. My hope is jsoup won't be relying on undocumented implementation details.

I'd be happy to provide an alternate version of this pull request if necessary.

**Comment by mccxj** [comment]
@cketti you are right. i already changed to normal try-cache implementation. thx.

**Comment by hameno** [comment]
Can we get this merged and a new release? :)

**Comment by mccxj** [comment]
@hameno I does not have right to merge it.😣

**Comment by hameno** [comment]
@mccxj I know...

**Comment by jhy** [comment]
Thanks, merged!

**Pull request merged**
