### PR TITLE
Maven plugins updated to latest versions

### PR DESCRIPTION
**Pull request by offa**
Maven plugins updated to latest versions.

### CODE REVIEW

**Comment by jhy** [comment]
Mmm I seem to remember hitting a whole bunch of problems with the Sonatype publish steps when I tried pushing these up before, and had to weave a specific set of versions. Will need to be careful with this. Thanks though!

**Comment by offa** [comment]
Are there any ways to test without killing something?

**Comment by jhy** [comment]
Yes, I will try a snapshot publish before merging.

**Comment by jhy** [comment]
Thanks, looks like it worked fine. I hit some issues finding the updated command line args for doing the deployment, but not with any of the versions specifically.

**Comment by offa** [comment]
Perfect!

**Comment by jhy** [comment]
But it looks like Travis is having a fitz on OpenJDK6 where one of the plugins needs a higher lang version?

**Comment by offa** [comment]
hmm, according to the [Apache Felix FAQ](https://felix.apache.org/documentation/faqs/apache-felix-bundle-plugin-faq.html#why-do-i-get-an-exception-unsupported-majorminor-version-490-when-i-build-with-a-14-or-earlier-jdk) everything >= JDK5 is good; but even earlier versions are still possible.

**Comment by offa** [comment]
I'll open an PR with a workaround (downgrade _maven-bundle-plugin_) in a moment.

**Comment by offa** [comment]
The [Dependencies List](http://felix.apache.org/components/bundle-plugin/dependencies.html) doesn't include any JDK7 related things. I've tested with a cleaned travis cache, but same problem.

**Comment by offa** [comment]
Reason found: http://maven.apache.org/docs/history.html

Since maven v3.3.1 JDK7 is required. Last JDK5: 3.1.1, JDK6: 3.2.5

**Pull request merged**
