### PR TITLE
add test case for hashcode in attribute

### PR DESCRIPTION
**Pull request by danglotb**
Hello,

I propose this changes to specify the [hashCode](https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/nodes/Attribute.java#L152) of the object `org.jsoup.nodes.Attribute`.

### CODE REVIEW

**Comment by cketti** [comment]
Why? The return value of `hashCode()` is typically an implementation detail, not part of the public API.

**Comment by danglotb** [comment]
> The return value of hashCode() is typically an implementation detail, not part of the public API.

I totally agree with you. 

But I think the `hashCode()` method worth a test case since it has to be deterministic.

**Comment by cketti** [comment]
Test the contract then. The documentation is very explicit on what that includes: https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#hashCode--

You might find this helpful: http://jqno.nl/equalsverifier/

**Comment by jhy** [comment]
Thanks. I agree with @cketti, this does not test the functionality or the contract, and the impl is trivial anyway.

**Pull request closed without merging**
