### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by CC11001100**
I think the logic should be so

### CODE REVIEW

**Comment by cketti** [comment]
It should probably be

```java
    public String setValue(String val) {
        String oldVal = this.val;
        if (parent != null) {
            int i = parent.indexOfKey(this.key);
            if (i != Attributes.NotFound)
                parent.vals[i] = val;
        }
        this.val = val;
        return oldVal;
    }
```

**Comment by cketti** [comment]
The class supports `null` values for `val`. Not allowing to set a `null` value via `setValue()` seems odd. My guess is the "must not be null" part ended up in the Javadoc due to copy&paste.

Side note: while looking into this I found a couple of issues with "null" values. See #1026

**Comment by jhy** [comment]
Sorry, coming to this late. I don't see what bug this is fixing? I have cleaned up the doc to confirm that it supports null values as input.

**Comment by cketti** [comment]
This was fixing a possible NPE. But it looks like you came up with your own fix in 1d663eeb1c0d1c08bcfe5d30f05170768bb0438e.

**Pull request closed without merging**
