### PR TITLE
extract valid char array for android

### PR DESCRIPTION
**Pull request by luoxg**

### CODE REVIEW

**Comment by jhy** [comment]
Hi -- could you please explain what the purpose / issue you're dealing with here is? What's Android specific? Can you add a test?

And, why do we have to force a path that does an array copy, if the content was already consumed correctly?

**Comment by lxgonyx** [comment]
String str2 = "60,63,120,109,108,32,118,101,114,115,105,111,110,61,34,49,46,48,34,32,101,110,99,111,100,105,110,103,61,34,117,116,102,45,56,34,63,62,60,33,68,79,67,84,89,80,69,32,104,116,109,108,32,80,85,66,76,73,67,32,34,45,47,47,87,51,67,47,47,68,84,68,32,88,72,84,77,76,32,49,46,49,47,47,69,78,34,13,10,32,32,34,104,116,116,112,58,47,47,119,119,119,46,119,51,46,111,114,103,47,84,82,47,120,104,116,109,108,49,49,47,68,84,68,47,120,104,116,109,108,49,49,46,100,116,100,34,62,60,104,116,109,108,32,120,109,108,110,115,61,34,104,116,116,112,58,47,47,119,119,119,46,119,51,46,111,114,103,47,49,57,57,57,47,120,104,116,109,108,34,32,120,109,108,58,108,97,110,103,61,34,101,110,34,62,60,104,101,97,100,62,13,10,32,32,32,32,32,32,32,32,60,109,101,116,97,32,104,116,116,112,45,101,113,117,105,118,61,34,67,111,110,116,101,110,116,45,84,121,112,101,34,32,99,111,110,116,101,110,116,61,34,116,101,120,116,47,104,116,109,108,59,32,99,104,97,114,115,101,116,61,85,84,70,45,56,34,47,62,13,10,32,32,32,32,32,32,32,32,60,109,101,116,97,32,110,97,109,101,61,34,99,97,108,105,98,114,101,58,99,111,118,101,114,34,32,99,111,110,116,101,110,116,61,34,116,114,117,101,34,47,62,13,10,32,32,32,32,32,32,32,32,60,116,105,116,108,101,62,67,111,118,101,114,60,47,116,105,116,108,101,62,13,10,32,32,32,32,32,32,32,32,60,108,105,110,107,32,114,101,108,61,34,115,116,121,108,101,115,104,101,101,116,34,32,104,114,101,102,61,34,107,105,110,100,108,101,58,102,108,111,119,58,48,48,48,76,63,109,105,109,101,61,116,101,120,116,47,99,115,115,34,32,116,121,112,101,61,34,116,101,120,116,47,99,115,115,34,32,116,105,116,108,101,61,34,111,118,101,114,114,105,100,101,95,99,115,115,34,47,62,13,10,32,32,32,32,60,47,104,101,97,100,62,60,98,111,100,121,32,97,105,100,61,34,73,51,81,77,48,34,62,13,10,32,32,32,32,32,32,32,32,60,100,105,118,32,97,105,100,61,34,73,51,81,77,49,34,62,13,10,32,32,32,32,32,32,32,32,32,32,32,32,60,105,109,103,32,115,114,99,61,34,107,105,110,100,108,101,58,102,108,111,119,58,48,48,48,77,63,109,105,109,101,61,105,109,97,103,101,47,115,118,103,43,120,109,108,34,47,62,13,10,32,32,32,32,32,32,32,32,60,47,100,105,118,62,13,10,60,47,98,111,100,121,62,60,47,104,116,109,108,62";

You can convert the above data to byte[] for parsing, and you will notice that running on Android will have a few more char's in the place I modified

**Comment by lxgonyx** [comment]
String[] split = str2.split(",");

        byte[] bytes = new byte[split.length];
        for (int i = 0; i < split.length; i++) {
            bytes[i] = Byte.parseByte(split[i]);
        }

        CharBuffer defaultDecoded = Charset.forName("utf-8").decode(ByteBuffer.wrap(bytes));
        This code has different results on Android and Java

**Review by blaquezzz — APPROVED** [review]

**Comment by jhy** [comment]
@blaquezzz why are you going around "approving" so many PRs? You're not adding value.

This PR is not "approved" and I'm still trying to understand it.

@luoxg / @lxgonyx, what is the relationship between your two accounts? Can you answer my other questions?

**Comment by luoxg** [comment]
> @blaquezzz why are you going around "approving" so many PRs? You're not adding value.
> 
> This PR is not "approved" and I'm still trying to understand it.
> 
> @luoxg / @lxgonyx, what is the relationship between your two accounts? Can you answer my other questions?
They're all mine. I forgot to switch。
I have uploaded two result image of Java and Android, you can have a look

image1
image1

**Comment by ehrmann** [comment]
Just doing a drive-by comment...

As far as I can tell, the existing code handles over-allocated arrays correctly with `arrayOffset()` and `limit()`:

```
parser.parseInput(new CharArrayReader(defaultDecoded.array(), defaultDecoded.arrayOffset(), defaultDecoded.limit()), baseUri);
```

*Maybe* `defaultDecoded.arrayOffset() + defaultDecoded.position(), defaultDecoded.remaining()` would be slightly better, but `position()` was `0` in the debugger screenshot, so I'm not sure what the issue is.

**Comment by luoxg** [comment]
> Just doing a drive-by comment...
> 
> As far as I can tell, the existing code handles over-allocated arrays correctly with `arrayOffset()` and `limit()`:
> 
> ```
> parser.parseInput(new CharArrayReader(defaultDecoded.array(), defaultDecoded.arrayOffset(), defaultDecoded.limit()), baseUri);
> ```
> 
> _Maybe_ `defaultDecoded.arrayOffset() + defaultDecoded.position(), defaultDecoded.remaining()` would be slightly better, but `position()` was `0` in the debugger screenshot, so I'm not sure what the issue is.

ArrayOffset has no effect on charBuffers. 
You can look at the wrap(char[] array,int offset, int length) and read(charBuffer target) methods in a charBuffer. Both use position() and limit(). 
And position in the screenshot is 0, because in our scenario, position is 0

**Comment by ehrmann** [comment]
> ArrayOffset has no effect on charBuffers.

That makes implementation assumptions about `HeapCharBuffer`. You can get a `CharBuffer` with an `arrayOffset` with `slice()`:

```
((CharBuffer) CharBuffer.wrap("hello".toCharArray()).position(1)).slice().arrayOffset()
```

That's obviously not what's happening here, though.

**Comment by jhy** [comment]
(Happy to review a PR if enough depth is provided to understand the issue and the resolution.)

**Pull request closed without merging**
