### PR TITLE
Set Request body to null when doing a redirecot

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fix for #872 
Set request body to null when doing a redirect

### CODE REVIEW

**Comment by jhy** [comment]
Thanks, looks good. Do you have an example site I can check on?

**Comment by Siedlerchr** [comment]
Hi,
I need this for the login to sharelatex.com.  In general it should be enough if you do a POST Request to a http website which replies with a 301 response.
The code I used:

```java
    private final String contentType = "application/json; charset=utf-8";
    private final JsonParser parser = new JsonParser();
    private final String userAgent = "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0";
    private Map<String, String> loginCookies = new HashMap<>();
    private String server;
    private String loginUrl;
    private String csrfToken;
    private String projectUrl;

   public String connectToServer(String server, String user, String password) throws IOException {

        this.server = server;
        this.loginUrl = server + "/login";
        Connection.Response crsfResponse;

        crsfResponse = Jsoup.connect(loginUrl).method(Method.GET)
                .execute();

        Document welcomePage = crsfResponse.parse();
        Map<String, String> welcomCookies = crsfResponse.cookies();

        csrfToken = welcomePage.select("input[name=_csrf]").attr("value");

        String json = "{\"_csrf\":" + JSONObject.quote(csrfToken)
                + ",\"email\":" + JSONObject.quote(user) + ",\"password\":" + JSONObject.quote(password) + "}";

        Connection.Response loginResponse = Jsoup.connect(loginUrl)
                .header("Content-Type", contentType)
                .header("Accept", "application/json, text/plain, */*")
                .cookies(welcomCookies)
                .method(Method.POST)
                .requestBody(json)
                .followRedirects(true)
                .ignoreContentType(true)
                .userAgent(userAgent)
                .execute();
```

**Comment by jhy** [comment]
Thanks for that, make sense.

**Comment by Siedlerchr** [comment]
In the linked issue I outlined the problem a bit more in detail:

> The problem is that whenever the request encounters a Location header, it switches the method to GET and wants to execute a 2nd request , but including all previous content from the first request, including the body. Which then leads to the error message.

**Pull request merged**
